name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "production"
        type: choice
        options:
          - qa
          - staging
          - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Define tags
        id: tags
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/savings-project-api"
          UNIQUE_TAG="${IMAGE_NAME}:${{ github.event.inputs.environment }}-${SHORT_SHA}"
          LATEST_TAG="${IMAGE_NAME}:${{ github.event.inputs.environment }}-latest"
          echo "UNIQUE_TAG=$UNIQUE_TAG" >> $GITHUB_ENV
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.UNIQUE_TAG }} .

      - name: Tag image as -latest for the environment
        run: docker tag ${{ env.UNIQUE_TAG }} ${{ env.LATEST_TAG }}

      - name: Push versioned image
        run: docker push ${{ env.UNIQUE_TAG }}

      - name: Push -latest tag
        run: docker push ${{ env.LATEST_TAG }}
